modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="GNU GENERAL PUBLIC LICENSE Version 3"
[[mods]] #mandatory
modId="graveyard" #mandatory
version="2.5.1" #mandatory
displayName="The Graveyard" #mandatory
logoFile="graveyard_logo.png" #optional
credits="" #optional
authors="Finallion" #optional
description='''
The Graveyard adds new structures, bosses, mobs and blocks to your minecraft world, themed around the graveyard!
'''

[[dependencies.graveyard]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.1.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.graveyard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.graveyard]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.34,)"
    ordering="NONE"
    side="BOTH"

